/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, number, Schema } from '../../schema';

/** This is a container type for any-of types. */
export type V1ElementsTransactionIntentionRequestAmountCase1 = number;

export const v1ElementsTransactionIntentionRequestAmountCase1Schema: Schema<V1ElementsTransactionIntentionRequestAmountCase1> = anyOf(
  [number()]
);

export namespace V1ElementsTransactionIntentionRequestAmountCase1 {
  /**
  * Validation method to narrow down union type to number type case.
  *
  * This is Number case.
  */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
