/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, string } from '../../schema';

/** This is a container type for one-of types. */
export type V1TokensAchRequest1AccountNumber = string;

export const v1TokensAchRequest1AccountNumberSchema: Schema<V1TokensAchRequest1AccountNumber> = oneOf(
  [string()]
);

export namespace V1TokensAchRequest1AccountNumber {
  /**
  * Validation method to narrow down union type to string type case.
  *
  * This is String case.
  */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
