/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountType1Enum
 */
export enum AccountType1Enum {
  Unknown = 'unknown',
  Checking = 'checking',
  Credit = 'credit',
  CashBenefit = 'cash_benefit',
  Snap = 'snap',
  Prepaid = 'prepaid',
  Savings = 'savings',
  SpendingPower = 'spending_power',
  Universal = 'universal',
}

/**
 * Schema for AccountType1Enum
 */
export const accountType1EnumSchema: Schema<AccountType1Enum> = stringEnum(AccountType1Enum);
