/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountTypeEnum
 */
export enum AccountTypeEnum {
  Checking = 'checking',
  Savings = 'savings',
}

/**
 * Schema for AccountTypeEnum
 */
export const accountTypeEnumSchema: Schema<AccountTypeEnum> = stringEnum(AccountTypeEnum);
