/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountType11Enum
 */
export enum AccountType11Enum {
  Checking = 'checking',
  Savings = 'savings',
}

/**
 * Schema for AccountType11Enum
 */
export const accountType11EnumSchema: Schema<AccountType11Enum> = stringEnum(AccountType11Enum);
