/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, nullable, number, optional, Schema } from '../schema';
import { AccountType1Enum, accountType1EnumSchema } from './accountType1Enum';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface AdditionalAmount {
  /** type of the amount [4S-Healthcare(Visa and MC Only), 4U-Prescription/Rx(Visa and MC Only), 4V-Vision/Optical(Visa Only), 4W-clinic/other qualified medical(Visa Only) ,4X-Dental(Visa Only)]. */
  type?: Type1Enum | null;
  /** The amount of additional amount. */
  amount?: number | null;
  /** Account Type */
  accountType?: AccountType1Enum | null;
  /** Currency Code */
  currency?: number | null;
  [key: string]: unknown;
}

export const additionalAmountSchema: Schema<AdditionalAmount> = expandoObject({
  type: ['type', optional(nullable(type1EnumSchema))],
  amount: ['amount', optional(nullable(number()))],
  accountType: ['account_type', optional(nullable(accountType1EnumSchema))],
  currency: ['currency', optional(nullable(number()))],
});
