/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface AuthRole {
  /** User ID */
  userId: string;
  /** Auth Role Code */
  authRoleCode: number;
  /** Auth Role User Code */
  code: number;
  /** Created Time Stamp */
  createdTs: number;
  /** Modified Time Stamp */
  modifiedTs: number;
  /** System generated id for user who created record */
  createdUserId?: string | null;
  /** System generated id for user who created record */
  modifiedUserId?: string | null;
  [key: string]: unknown;
}

export const authRoleSchema: Schema<AuthRole> = expandoObject({
  userId: ['user_id', string()],
  authRoleCode: ['auth_role_code', number()],
  code: ['code', number()],
  createdTs: ['created_ts', number()],
  modifiedTs: ['modified_ts', number()],
  createdUserId: ['created_user_id', optional(nullable(string()))],
  modifiedUserId: ['modified_user_id', optional(nullable(string()))],
});
