/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  optional,
  Schema,
  string,
} from '../schema';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum';

/** Array of bank account objects. */
export interface BankAccount {
  /** Account holder name. */
  accountHolderName: string;
  /** Nine-digit Bank routing number. */
  routingNumber: string;
  /** Account number. */
  accountNumber: string;
  /** Flag indicating whether or not the account is the primary account. Only one account can be marked as primary. */
  isPrimary?: boolean;
  /** Account type. Either "checking" or "savings" */
  accountType: AccountTypeEnum;
  /** Array of deposit types. ('fees', 'adjustments', 'returns') */
  altDepositTypes?: string[];
  [key: string]: unknown;
}

export const bankAccountSchema: Schema<BankAccount> = expandoObject({
  accountHolderName: ['account_holder_name', string()],
  routingNumber: ['routing_number', string()],
  accountNumber: ['account_number', string()],
  isPrimary: ['is_primary', optional(boolean())],
  accountType: ['account_type', accountTypeEnumSchema],
  altDepositTypes: ['alt_deposit_types', optional(array(string()))],
});
