/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema } from '../schema';
import { MethodEnum, methodEnumSchema } from './methodEnum';
import { Values40Enum, values40EnumSchema } from './values40Enum';

export interface Conditions16 {
  method?: MethodEnum;
  values?: Values40Enum;
  [key: string]: unknown;
}

export const conditions16Schema: Schema<Conditions16> = expandoObject({
  method: ['method', optional(methodEnumSchema)],
  values: ['values', optional(values40EnumSchema)],
});
