/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema } from '../schema';
import { Method43Enum, method43EnumSchema } from './method43Enum';
import { Values48Enum, values48EnumSchema } from './values48Enum';

export interface Conditions171 {
  method?: Method43Enum;
  values?: Values48Enum;
  [key: string]: unknown;
}

export const conditions171Schema: Schema<Conditions171> = expandoObject({
  method: ['method', optional(method43EnumSchema)],
  values: ['values', optional(values48EnumSchema)],
});
