/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema } from '../schema';
import { Method43Enum, method43EnumSchema } from './method43Enum';
import { Values41Enum, values41EnumSchema } from './values41Enum';

export interface Conditions161 {
  method?: Method43Enum;
  values?: Values41Enum;
  [key: string]: unknown;
}

export const conditions161Schema: Schema<Conditions161> = expandoObject({
  method: ['method', optional(method43EnumSchema)],
  values: ['values', optional(values41EnumSchema)],
});
