/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema, string } from '../schema';

export interface Data27 {
  id: string;
  userId: string;
  hash: string;
  /** Created Time Stamp */
  createdTs: number;
  [key: string]: unknown;
}

export const data27Schema: Schema<Data27> = expandoObject({
  id: ['id', string()],
  userId: ['user_id', string()],
  hash: ['hash', string()],
  createdTs: ['created_ts', number()],
});
