/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { BillingAddress5, billingAddress5Schema } from './billingAddress5';
import {
  Data20LocationId,
  data20LocationIdSchema,
} from './containers/data20LocationId';

export interface Data20 {
  /** Account holder name */
  accountHolderName?: string | null;
  /** The Expiration Date for the credit card. */
  expDate: string;
  /** CVV */
  cvv?: string | null;
  /** Account number */
  accountNumber: string;
  /** Billing Address Object */
  billingAddress?: BillingAddress5;
  /** Used to associate the Ticket with a Contact. */
  contactId?: string | null;
  /** Used to associate the Ticket with a Contact. */
  contactApiId?: string | null;
  /** A valid Location Id associated with the Contact for this Ticket */
  locationId?: Data20LocationId;
  /** Location Api Id */
  locationApiId?: string | null;
  /** A unique, system-generated identifier for the Ticket. */
  id: string;
  /** Created Time Stamp */
  createdTs: number;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const data20Schema: Schema<Data20> = expandoObject({
  accountHolderName: ['account_holder_name', optional(nullable(string()))],
  expDate: ['exp_date', string()],
  cvv: ['cvv', optional(nullable(string()))],
  accountNumber: ['account_number', string()],
  billingAddress: [
    'billing_address',
    optional(lazy(() => billingAddress5Schema)),
  ],
  contactId: ['contact_id', optional(nullable(string()))],
  contactApiId: ['contact_api_id', optional(nullable(string()))],
  locationId: ['location_id', optional(data20LocationIdSchema)],
  locationApiId: ['location_api_id', optional(nullable(string()))],
  id: ['id', string()],
  createdTs: ['created_ts', number()],
  createdUserId: ['created_user_id', optional(nullable(string()))],
});
