/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface Data33 {
  /** String formatted merchantSession object.  Needs to be passed to the session.completeMerchantValidation event in JS. */
  merchantSession?: string;
  [key: string]: unknown;
}

export const data33Schema: Schema<Data33> = expandoObject({
  merchantSession: ['merchantSession', optional(string())],
});
