/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { Changelog, changelogSchema } from './changelog';
import { CreatedUser, createdUserSchema } from './createdUser';
import { Location, locationSchema } from './location';
import { ReasonCode, reasonCodeSchema } from './reasonCode';
import { Signature, signatureSchema } from './signature';
import { Terminal, terminalSchema } from './terminal';

export interface Data6 {
  /** Location ID */
  locationId: string;
  /** Terminal ID */
  terminalId: string;
  /** Set to true or 1 to require a signature from the customer */
  requireSignature: boolean;
  /** Can be used for associating record to external systems. Must be unique per location. */
  deviceTermApiId?: string | null;
  /** This is the message that is displayed on the screen when prompting for a signature. */
  termsConditions: string;
  /** Device term ID */
  id: string;
  /** Reason code ID */
  reasonCodeId: number;
  /** Signature Information on `expand` */
  signature?: Signature;
  /** Created Time Stamp */
  createdTs: number;
  /** Modified Time Stamp */
  modifiedTs: number;
  /** System generated id for user who created record */
  createdUserId: string;
  /** User Information on `expand` */
  createdUser?: CreatedUser;
  /** Location Information on `expand` */
  location?: Location;
  /** Terminal Information on `expand` */
  terminal?: Terminal;
  /** Changelog Information on `expand` */
  changelogs?: Changelog[];
  /** Reason Code Information on `expand` */
  reasonCode?: ReasonCode;
  [key: string]: unknown;
}

export const data6Schema: Schema<Data6> = expandoObject({
  locationId: ['location_id', string()],
  terminalId: ['terminal_id', string()],
  requireSignature: ['require_signature', boolean()],
  deviceTermApiId: ['device_term_api_id', optional(nullable(string()))],
  termsConditions: ['terms_conditions', string()],
  id: ['id', string()],
  reasonCodeId: ['reason_code_id', number()],
  signature: ['signature', optional(lazy(() => signatureSchema))],
  createdTs: ['created_ts', number()],
  modifiedTs: ['modified_ts', number()],
  createdUserId: ['created_user_id', string()],
  createdUser: ['created_user', optional(lazy(() => createdUserSchema))],
  location: ['location', optional(lazy(() => locationSchema))],
  terminal: ['terminal', optional(lazy(() => terminalSchema))],
  changelogs: ['changelogs', optional(array(lazy(() => changelogSchema)))],
  reasonCode: ['reason_code', optional(lazy(() => reasonCodeSchema))],
});
