/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface Data28 {
  /** User Api Key */
  userApiKey: string;
  [key: string]: unknown;
}

export const data28Schema: Schema<Data28> = expandoObject({
  userApiKey: ['user_api_key', string()],
});
