/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, Schema, string } from '../schema';
import { Level3Data, level3DataSchema } from './level3Data';

export interface Data24 {
  /** Level 3 ID */
  id: string;
  /** Transaction ID */
  transactionId: string;
  /** Level 3 data object */
  level3Data: Level3Data;
  [key: string]: unknown;
}

export const data24Schema: Schema<Data24> = expandoObject({
  id: ['id', string()],
  transactionId: ['transaction_id', string()],
  level3Data: ['level3_data', lazy(() => level3DataSchema)],
});
