/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  nullable,
  optional,
  Schema,
  string,
} from '../schema';

export interface Data15 {
  /** Quick Invoice ID */
  id: string;
  /** Email Log Id */
  emailLogId?: string | null;
  /** SMS Log Id */
  smsLogId?: string | null;
  /** Success */
  success?: boolean;
  /** SMS Success */
  smsSuccess?: boolean;
  /** Email */
  email?: string | null;
  [key: string]: unknown;
}

export const data15Schema: Schema<Data15> = expandoObject({
  id: ['id', string()],
  emailLogId: ['email_log_id', optional(nullable(string()))],
  smsLogId: ['sms_log_id', optional(nullable(string()))],
  success: ['success', optional(boolean())],
  smsSuccess: ['sms_success', optional(boolean())],
  email: ['email', optional(nullable(string()))],
});
