/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Expand101Enum
 */
export enum Expand101Enum {
  Postbacklogs = 'postbacklogs',
  BasicAuthUsername = 'basic_auth_username',
  BasicAuthPassword = 'basic_auth_password',
}

/**
 * Schema for Expand101Enum
 */
export const expand101EnumSchema: Schema<Expand101Enum> = stringEnum(Expand101Enum);
