/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  nullable,
  optional,
  Schema,
  string,
} from '../schema';

export interface Field16 {
  /** id */
  id: string;
  /** Label */
  label: string;
  /** Field Type */
  fieldType: string;
  /** Position */
  position: string[];
  /** Required */
  required?: boolean;
  /** Read Only */
  readonly?: boolean;
  /** Visible */
  visible?: boolean;
  /** Value */
  value?: string | null;
  [key: string]: unknown;
}

export const field16Schema: Schema<Field16> = expandoObject({
  id: ['id', string()],
  label: ['label', string()],
  fieldType: ['field_type', string()],
  position: ['position', array(string())],
  required: ['required', optional(boolean())],
  readonly: ['readonly', optional(boolean())],
  visible: ['visible', optional(boolean())],
  value: ['value', optional(nullable(string()))],
});
