/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field29Enum
 */
export enum Field29Enum {
  LocationId = 'location_id',
  TerminalId = 'terminal_id',
  RequireSignature = 'require_signature',
  DeviceTermApiId = 'device_term_api_id',
  TermsConditions = 'terms_conditions',
  Id = 'id',
  ReasonCodeId = 'reason_code_id',
  Signature = 'signature',
  CreatedTs = 'created_ts',
  ModifiedTs = 'modified_ts',
  CreatedUserId = 'created_user_id',
  CreatedUser = 'created_user',
  Location = 'location',
  Terminal = 'terminal',
  Changelogs = 'changelogs',
  ReasonCode = 'reason_code',
}

/**
 * Schema for Field29Enum
 */
export const field29EnumSchema: Schema<Field29Enum> = stringEnum(Field29Enum);
