/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field35Enum
 */
export enum Field35Enum {
  LocationId = 'location_id',
  CcProductTransactionId = 'cc_product_transaction_id',
  Email = 'email',
  AmountDue = 'amount_due',
  LocationApiId = 'location_api_id',
  ContactId = 'contact_id',
  ContactApiId = 'contact_api_id',
  PaylinkApiId = 'paylink_api_id',
  AchProductTransactionId = 'ach_product_transaction_id',
  ExpireDate = 'expire_date',
  DisplayProductTransactionReceiptDetails = 'display_product_transaction_receipt_details',
  DisplayBillingFields = 'display_billing_fields',
  DeliveryMethod = 'delivery_method',
  CellPhone = 'cell_phone',
  Description = 'description',
  StoreToken = 'store_token',
  StoreTokenTitle = 'store_token_title',
  PaylinkAction = 'paylink_action',
  BankFundedOnlyOverride = 'bank_funded_only_override',
  Tags = 'tags',
  Id = 'id',
  StatusId = 'status_id',
  StatusCode = 'status_code',
  Active = 'active',
  CreatedTs = 'created_ts',
  ModifiedTs = 'modified_ts',
  CreatedUserId = 'created_user_id',
  ModifiedUserId = 'modified_user_id',
  AllTags = 'all_tags',
  Location = 'location',
  CreatedUser = 'created_user',
  ModifiedUser = 'modified_user',
  Changelogs = 'changelogs',
  Contact = 'contact',
  LogEmails = 'log_emails',
  LogSms = 'log_sms',
  Transactions = 'transactions',
  CcProductTransaction = 'cc_product_transaction',
  AchProductTransaction = 'ach_product_transaction',
  EmailBlacklist = 'email_blacklist',
  SmsBlacklist = 'sms_blacklist',
  PaymentUrl = 'payment_url',
}

/**
 * Schema for Field35Enum
 */
export const field35EnumSchema: Schema<Field35Enum> = stringEnum(Field35Enum);
