/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';
import { OrderEnum, orderEnumSchema } from './orderEnum';

export interface Field {
  /** Field name used on the sort */
  field: string;
  /** Sort direction ASC/DESC */
  order: OrderEnum;
  [key: string]: unknown;
}

export const fieldSchema: Schema<Field> = expandoObject({
  field: ['field', string()],
  order: ['order', orderEnumSchema],
});
