/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field41Enum
 */
export enum Field41Enum {
  Signature = 'signature',
  Resource = 'resource',
  ResourceId = 'resource_id',
  Id = 'id',
  CreatedTs = 'created_ts',
  ModifiedTs = 'modified_ts',
  RawSignature = 'raw_signature',
}

/**
 * Schema for Field41Enum
 */
export const field41EnumSchema: Schema<Field41Enum> = stringEnum(Field41Enum);
