/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Field28Enum
 */
export enum Field28Enum {
  Id = 'id',
  DeclinedTransactionId = 'declined_transaction_id',
  PaymentTransactionId = 'payment_transaction_id',
  Status = 'status',
  RecurringId = 'recurring_id',
  CreatedTs = 'created_ts',
  CreatedUserId = 'created_user_id',
  ModifiedTs = 'modified_ts',
  ModifiedUserId = 'modified_user_id',
  Recurring = 'recurring',
  PaymentTransaction = 'payment_transaction',
  DeclinedTransaction = 'declined_transaction',
}

/**
 * Schema for Field28Enum
 */
export const field28EnumSchema: Schema<Field28Enum> = stringEnum(Field28Enum);
