/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema } from '../schema';
import { Field16, field16Schema } from './field16';
import { Settings, settingsSchema } from './settings';

/** Header */
export interface Header {
  settings: Settings;
  fields: Field16[];
  [key: string]: unknown;
}

export const headerSchema: Schema<Header> = expandoObject({
  settings: ['settings', lazy(() => settingsSchema)],
  fields: ['fields', array(lazy(() => field16Schema))],
});
