/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema } from '../schema';
import {
  Joi16Conditions,
  joi16ConditionsSchema,
} from './containers/joi16Conditions';

export interface Joi16 {
  conditions?: Joi16Conditions;
  [key: string]: unknown;
}

export const joi16Schema: Schema<Joi16> = expandoObject({
  conditions: ['conditions', optional(lazy(() => joi16ConditionsSchema))],
});
