/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

/** Pagination page links */
export interface Links {
  /** Object type */
  type: string;
  /** Link to the first page */
  first: string;
  /** Link to the previous page */
  previous: string;
  /** Link to the last page */
  last: string;
  [key: string]: unknown;
}

export const linksSchema: Schema<Links> = expandoObject({
  type: ['type', string()],
  first: ['first', string()],
  previous: ['previous', string()],
  last: ['last', string()],
});
