/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Log Sms Information on `expand` */
export interface LogSms {
  /** Log Sms Id */
  id: string;
  /** Body */
  body?: string | null;
  /** Reason Model */
  reasonModel: string;
  /** Reason Model ID */
  reasonModelId: string;
  /** Provider ID */
  providerId: string;
  /** Status */
  status: string;
  /** Sender */
  sender: string;
  /** Recipient */
  recipient: string;
  /** Created Time Stamp */
  createdTs: number;
  /** User ID Created the register */
  createdUserId: string;
  [key: string]: unknown;
}

export const logSmsSchema: Schema<LogSms> = expandoObject({
  id: ['id', string()],
  body: ['body', optional(nullable(string()))],
  reasonModel: ['reason_model', string()],
  reasonModelId: ['reason_model_id', string()],
  providerId: ['provider_id', string()],
  status: ['status', string()],
  sender: ['sender', string()],
  recipient: ['recipient', string()],
  createdTs: ['created_ts', number()],
  createdUserId: ['created_user_id', string()],
});
