/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Method43Enum
 */
export enum Method43Enum {
  And = 'and',
}

/**
 * Schema for Method43Enum
 */
export const method43EnumSchema: Schema<Method43Enum> = stringEnum(Method43Enum);
