/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema, string } from '../schema';

/** Pagination info */
export interface Pagination {
  /** Object type */
  type: string;
  /** Total records count */
  totalCount?: number;
  /** Total page count */
  pageCount?: number;
  /** Current page */
  pageNumber?: number;
  /** Page size */
  pageSize?: number;
  [key: string]: unknown;
}

export const paginationSchema: Schema<Pagination> = expandoObject({
  type: ['type', string()],
  totalCount: ['total_count', optional(number())],
  pageCount: ['page_count', optional(number())],
  pageNumber: ['page_number', optional(number())],
  pageSize: ['page_size', optional(number())],
});
