/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentMethod6Enum
 */
export enum PaymentMethod6Enum {
  Cc = 'cc',
  Ach = 'ach',
}

/**
 * Schema for PaymentMethod6Enum
 */
export const paymentMethod6EnumSchema: Schema<PaymentMethod6Enum> = stringEnum(PaymentMethod6Enum);
