/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentMethod13Enum
 */
export enum PaymentMethod13Enum {
  Cc = 'cc',
  Ach = 'ach',
}

/**
 * Schema for PaymentMethod13Enum
 */
export const paymentMethod13EnumSchema: Schema<PaymentMethod13Enum> = stringEnum(PaymentMethod13Enum);
