/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data9, data9Schema } from './data9';

export interface ResponseFullboarding {
  /** Resource Type */
  type: string;
  data?: Data9;
  [key: string]: unknown;
}

export const responseFullboardingSchema: Schema<ResponseFullboarding> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data9Schema))],
  }
);
