/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data12, data12Schema } from './data12';

export interface ResponseOnboarding {
  /** Resource Type */
  type: string;
  data?: Data12;
  [key: string]: unknown;
}

export const responseOnboardingSchema: Schema<ResponseOnboarding> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data12Schema))],
  }
);
