/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data32, data32Schema } from './data32';

export interface ResponseMerchantDetails {
  /** Resource Type */
  type: string;
  data?: Data32;
  [key: string]: unknown;
}

export const responseMerchantDetailsSchema: Schema<ResponseMerchantDetails> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data32Schema))],
  }
);
