/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data34, data34Schema } from './data34';

export interface ResponseWebhook {
  /** Resource Type */
  type: string;
  data?: Data34;
  [key: string]: unknown;
}

export const responseWebhookSchema: Schema<ResponseWebhook> = expandoObject({
  type: ['type', string()],
  data: ['data', optional(lazy(() => data34Schema))],
});
