/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data21, data21Schema } from './data21';

export interface ResponseToken {
  /** Resource Type */
  type: string;
  data?: Data21;
  [key: string]: unknown;
}

export const responseTokenSchema: Schema<ResponseToken> = expandoObject({
  type: ['type', string()],
  data: ['data', optional(lazy(() => data21Schema))],
});
