/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data8, data8Schema } from './data8';

export interface ResponseTransactionIntention {
  /** Resource Type */
  type: string;
  data?: Data8;
  [key: string]: unknown;
}

export const responseTransactionIntentionSchema: Schema<ResponseTransactionIntention> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data8Schema))],
  }
);
