/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data28, data28Schema } from './data28';

export interface ResponseUserApiKey {
  /** Resource Type */
  type: string;
  data?: Data28;
  [key: string]: unknown;
}

export const responseUserApiKeySchema: Schema<ResponseUserApiKey> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data28Schema))],
  }
);
