/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data22, data22Schema } from './data22';

export interface ResponseTransaction {
  /** Resource Type */
  type: string;
  data?: Data22;
  [key: string]: unknown;
}

export const responseTransactionSchema: Schema<ResponseTransaction> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data22Schema))],
  }
);
