/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data15, data15Schema } from './data15';

export interface ResponseQuickInvoiceResend {
  /** Resource Type */
  type: string;
  data?: Data15;
  [key: string]: unknown;
}

export const responseQuickInvoiceResendSchema: Schema<ResponseQuickInvoiceResend> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data15Schema))],
  }
);
