/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data13, data13Schema } from './data13';

export interface ResponsePaylink {
  /** Resource Type */
  type: string;
  data?: Data13;
  [key: string]: unknown;
}

export const responsePaylinkSchema: Schema<ResponsePaylink> = expandoObject({
  type: ['type', string()],
  data: ['data', optional(lazy(() => data13Schema))],
});
