/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data27, data27Schema } from './data27';

export interface ResponseSendVerification {
  /** Resource Type */
  type: string;
  data?: Data27;
  [key: string]: unknown;
}

export const responseSendVerificationSchema: Schema<ResponseSendVerification> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data27Schema))],
  }
);
