/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data29, data29Schema } from './data29';

export interface ResponseUser {
  /** Resource Type */
  type: string;
  data?: Data29;
  [key: string]: unknown;
}

export const responseUserSchema: Schema<ResponseUser> = expandoObject({
  type: ['type', string()],
  data: ['data', optional(lazy(() => data29Schema))],
});
