/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data7, data7Schema } from './data7';

export interface ResponseTicketIntention {
  /** Resource Type */
  type: string;
  data?: Data7;
  [key: string]: unknown;
}

export const responseTicketIntentionSchema: Schema<ResponseTicketIntention> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data7Schema))],
  }
);
