/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data3, data3Schema } from './data3';

export interface ResponseDeclinedRecurringTransaction {
  /** Resource Type */
  type: string;
  data?: Data3;
  [key: string]: unknown;
}

export const responseDeclinedRecurringTransactionSchema: Schema<ResponseDeclinedRecurringTransaction> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data3Schema))],
  }
);
