/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data17, data17Schema } from './data17';

export interface ResponseSignature {
  /** Resource Type */
  type: string;
  data?: Data17;
  [key: string]: unknown;
}

export const responseSignatureSchema: Schema<ResponseSignature> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data17Schema))],
  }
);
