/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data23, data23Schema } from './data23';

export interface ResponseTransactionBinInfo {
  /** Resource Type */
  type: string;
  data?: Data23;
  [key: string]: unknown;
}

export const responseTransactionBinInfoSchema: Schema<ResponseTransactionBinInfo> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data23Schema))],
  }
);
