/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data20, data20Schema } from './data20';

export interface ResponseTicket {
  /** Resource Type */
  type: string;
  data?: Data20;
  [key: string]: unknown;
}

export const responseTicketSchema: Schema<ResponseTicket> = expandoObject({
  type: ['type', string()],
  data: ['data', optional(lazy(() => data20Schema))],
});
