/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data33, data33Schema } from './data33';

export interface ResponseApplePayValidateMerchant {
  /** Resource Type */
  type: string;
  data?: Data33;
  [key: string]: unknown;
}

export const responseApplePayValidateMerchantSchema: Schema<ResponseApplePayValidateMerchant> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data33Schema))],
  }
);
