/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, optional, Schema, string } from '../schema';
import { Data11, data11Schema } from './data11';

export interface ResponseLocationInfo {
  /** Resource Type */
  type: string;
  data?: Data11;
  [key: string]: unknown;
}

export const responseLocationInfoSchema: Schema<ResponseLocationInfo> = expandoObject(
  {
    type: ['type', string()],
    data: ['data', optional(lazy(() => data11Schema))],
  }
);
