/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, expandoObject, number, Schema } from '../schema';

export interface Settings {
  /** Enabled */
  enabled: boolean;
  /** Columns */
  columns: number;
  /** Rows */
  rows: number;
  [key: string]: unknown;
}

export const settingsSchema: Schema<Settings> = expandoObject({
  enabled: ['enabled', boolean()],
  columns: ['columns', number()],
  rows: ['rows', number()],
});
