/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema, string } from '../schema';
import { ResourceEnum, resourceEnumSchema } from './resourceEnum';

/** Signature Information on `expand` */
export interface Signature {
  /** Signature */
  signature: string;
  /** Resource */
  resource: ResourceEnum;
  /** Resource ID */
  resourceId: string;
  /** Signature ID */
  id: string;
  /** Created Time Stamp */
  createdTs: number;
  /** Modified Time Stamp */
  modifiedTs: number;
  [key: string]: unknown;
}

export const signatureSchema: Schema<Signature> = expandoObject({
  signature: ['signature', string()],
  resource: ['resource', resourceEnumSchema],
  resourceId: ['resource_id', string()],
  id: ['id', string()],
  createdTs: ['created_ts', number()],
  modifiedTs: ['modified_ts', number()],
});
