/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema, string } from '../schema';
import { Field, fieldSchema } from './field';

/** Sort information used on the results */
export interface Sort {
  /** Object type */
  type: string;
  /** [object Object] */
  fields: Field[];
  [key: string]: unknown;
}

export const sortSchema: Schema<Sort> = expandoObject({
  type: ['type', string()],
  fields: ['fields', array(lazy(() => fieldSchema))],
});
