/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface Status5 {
  /** Response code for API response. */
  responseCode?: string;
  /** Reason code for API response. */
  reasonCode?: string;
  /** Reason text returned for any errors from API call. */
  reasonText?: string;
  [key: string]: unknown;
}

export const status5Schema: Schema<Status5> = expandoObject({
  responseCode: ['response_code', optional(string())],
  reasonCode: ['reason_code', optional(string())],
  reasonText: ['reason_text', optional(string())],
});
