/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema, string } from '../schema';

export interface Tag {
  /** Location ID */
  locationId: string;
  /** Tag Title */
  title: string;
  /** Tag ID */
  id: string;
  /** Created Time Stamp */
  createdTs: number;
  /** Modified Time Stamp */
  modifiedTs: number;
  [key: string]: unknown;
}

export const tagSchema: Schema<Tag> = expandoObject({
  locationId: ['location_id', string()],
  title: ['title', string()],
  id: ['id', string()],
  createdTs: ['created_ts', number()],
  modifiedTs: ['modified_ts', number()],
});
