/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Terminal Application Information on `expand` */
export interface TerminalApplication {
  /** Standalone */
  standalone: boolean;
  /** Emv Capable */
  emvCapable: boolean;
  /** Nfc Capable */
  nfcCapable: boolean;
  /** Pin Capable */
  pinCapable: boolean;
  /** Print Capable */
  printCapable: boolean;
  /** Msr Capable */
  msrCapable: boolean;
  /** Sig Capture Capable */
  sigCaptureCapable: boolean;
  /** Mpos Terminal */
  mposTerminal: boolean;
  /** Title */
  title?: string | null;
  /** Description */
  description?: string | null;
  /** Terminal Application Id */
  id: string;
  /** Created Time Stamp */
  createdTs?: number | null;
  /** Modified Time Stamp */
  modifiedTs?: number | null;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const terminalApplicationSchema: Schema<TerminalApplication> = expandoObject(
  {
    standalone: ['standalone', boolean()],
    emvCapable: ['emv_capable', boolean()],
    nfcCapable: ['nfc_capable', boolean()],
    pinCapable: ['pin_capable', boolean()],
    printCapable: ['print_capable', boolean()],
    msrCapable: ['msr_capable', boolean()],
    sigCaptureCapable: ['sig_capture_capable', boolean()],
    mposTerminal: ['mpos_terminal', boolean()],
    title: ['title', optional(nullable(string()))],
    description: ['description', optional(nullable(string()))],
    id: ['id', string()],
    createdTs: ['created_ts', optional(nullable(number()))],
    modifiedTs: ['modified_ts', optional(nullable(number()))],
    createdUserId: ['created_user_id', optional(nullable(string()))],
  }
);
