/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface TerminalRouter {
  /** Mac Address */
  macAddress?: string;
  /** Location ID */
  locationId: string;
  /** Location API ID */
  locationApiId?: string | null;
  /** Terminal Router ID */
  id: string;
  /** Created Time Stamp */
  createdTs: number;
  /** Modified Time Stamp */
  modifiedTs: number;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const terminalRouterSchema: Schema<TerminalRouter> = expandoObject({
  macAddress: ['mac_address', optional(string())],
  locationId: ['location_id', string()],
  locationApiId: ['location_api_id', optional(nullable(string()))],
  id: ['id', string()],
  createdTs: ['created_ts', number()],
  modifiedTs: ['modified_ts', number()],
  createdUserId: ['created_user_id', optional(nullable(string()))],
});
