/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface TransactionSplit {
  /** Transaction ID */
  transactionId: string;
  /** Contact ID */
  contactId: string;
  /** Amount */
  amount: number;
  /** Transaction Splits ID */
  id: string;
  /** Created Time Stamp */
  createdTs: number;
  /** User ID Created the register */
  createdUserId?: string | null;
  [key: string]: unknown;
}

export const transactionSplitSchema: Schema<TransactionSplit> = expandoObject({
  transactionId: ['transaction_id', string()],
  contactId: ['contact_id', string()],
  amount: ['amount', number()],
  id: ['id', string()],
  createdTs: ['created_ts', number()],
  createdUserId: ['created_user_id', optional(nullable(string()))],
});
