/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type1Enum
 */
export enum Type1Enum {
  Cashback = 'cashback',
  Surcharge = 'surcharge',
  Healthcare = 'healthcare',
  Transit = 'transit',
  RX = 'RX',
  Vision = 'vision',
  Clinical = 'clinical',
  Copay = 'copay',
  Dental = 'dental',
  Tax = 'tax',
  Fee = 'fee',
}

/**
 * Schema for Type1Enum
 */
export const type1EnumSchema: Schema<Type1Enum> = stringEnum(Type1Enum);
