/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  expandoObject,
  nullable,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Type Information on `expand` */
export interface Type6 {
  /** ID */
  id?: number | null;
  /** Title */
  title?: string;
  [key: string]: unknown;
}

export const type6Schema: Schema<Type6> = expandoObject({
  id: ['id', optional(nullable(number()))],
  title: ['title', optional(string())],
});
