/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Values41Enum
 */
export enum Values41Enum {
  AccountNumber = 'account_number',
  AccountHolderName = 'account_holder_name',
  RoutingNumber = 'routing_number',
}

/**
 * Schema for Values41Enum
 */
export const values41EnumSchema: Schema<Values41Enum> = stringEnum(Values41Enum);
