/**
 * Fortis APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Values48Enum
 */
export enum Values48Enum {
  AccountNumber = 'account_number',
  ExpDate = 'exp_date',
}

/**
 * Schema for Values48Enum
 */
export const values48EnumSchema: Schema<Values48Enum> = stringEnum(Values48Enum);
